language: python
python: "3.6"
cache: pip
before_install:
  - "pip install -U pip"
install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/src
  - pip install -r requirements.txt
  - pip install .
script:
  - python tests/test_read_ibt.py
  - python tests/test_sweep.py
branches:
  only:
    - master
